version: '3.7'

services:
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - 5000:5000
    networks:
      - flask_network
    volumes: 
      - /home/pme/static:/code/static/


  db:
    image: postgres:13
    restart: always
    ports:
      - 5433:5432
    networks:
      - flask_network
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=50050275
      - POSTGRES_DB=pme
    volumes:
      - postgres_data:/var/lib/postgresql/data
networks:
  flask_network:

volumes:
  postgres_data:




